### ISSUE TITLE
Retrieve postgresql messages / logging

### ISSUE THREAD

**Issue by Jezternz** [rickbergfalk/postgrator#103]
Is there any way to getmessages that are output from the postgresql upgrade scripts?

**Comment by rickbergfalk** [comment]
I don't believe so. I'd be open to a PR if you wanted to take a shot at it.

**Comment by rickbergfalk** [comment]
With v4.3 the `execQuery` option allows implementing the underlying query execution handling. Its possible to capture this if it is something someone is looking to do, since it is up to the postgrator user to implement the query execution logic.
