### ISSUE TITLE
Option to skip MD5 hashing

### ISSUE THREAD

**Issue by senner007** [rickbergfalk/postgrator#108]
To apply migrations when testing

**Comment by rickbergfalk** [comment]
Hi @senner007 - I think this already exists with the `validateChecksums` setting. Is this what you were looking for? https://github.com/rickbergfalk/postgrator#checksum-validation

**Comment by senner007** [comment]
@rickbergfalk 
Hi.
I'm not sure what that does, but it didn't do what I was looking for. I could go through the source of course. 
I'm talking about not creating the checksum table at all when I need to build and destroy the table before each test.

**Comment by rickbergfalk** [comment]
Ah ok that helps. 

I don't think turning off the setting prevents the table from being created, it just prevents the hash from being generated and checked. 

Not creating the table at all would require a change I'm pretty sure.

**Comment by senner007** [comment]
Yes. So would you consider it, or can I make a pr?

**Comment by rickbergfalk** [comment]
Sure! If you'd like to open a PR go for it. It might be a while til I get to it personally.

**Comment by rickbergfalk** [comment]
@senner007 I'm going to close this issue out. I had forgotten the md5 hashing is just column on the schema version table. It would add some complexity to the project to not add the md5 column if the feature was turned off.
