### ISSUE TITLE
MD5 checksum error for migration that is not in schemaversion

### ISSUE THREAD

**Issue by runemadsen** [rickbergfalk/postgrator#112]
First of all, thanks for an incredible library. We have been using it in production for years, and it has been working great for us!

I'm running into an odd problem. I have the follow migrations:

```
029.do.something1.sql
030.do.something2.sql
031.do.something3.sql
032.do.something4.sql
033.do.something5.sql
```

Now, I have a machine where `29`, `31`, `32`, `33` has run, but not `30`. I know this because this is my `schemaversion` table:

```js
[ 
  //...
  { version: '29',
    name: 'something1',
    md5: '292ee0aaaecc651f2cf8703eeac1eab1',
    runAt: 2020-03-23T18:14:16.853Z },
  { version: '31',
    name: 'something3',
    md5: 'c02a792070b5e1e4bf7727b1f08c826e',
    runAt: 2020-07-15T14:02:26.445Z },
  { version: '32',
    name: 'something4',
    md5: 'c0033cc723234df8e8ed35308a132304',
    runAt: 2020-07-15T14:02:26.454Z },
  { version: '33',
    name: 'something5',
    md5: 'e164eb615dfb4cd6a92b56c891c8f8a0',
    runAt: 2020-07-15T14:02:26.471Z } ]
```

However, when I run the migrate script, I'm getting the follow error:

```
(node:54) UnhandledPromiseRejectionWarning: Error: MD5 checksum failed for migration [30]
    at sequence.then.then.then (/usr/local/app/node_modules/postgrator/postgrator.js:194:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

How can this be? When `30` is not in `schemaversion`, shouldn't it just work?

I am running `postgrator` version `3.6.0`. Is this something that is fixed in the newer versions?

Thanks!

**Comment by runemadsen** [comment]
I realized that the version numbers must be sequential, so I'm closing this issue. Thanks again!

**Comment by rickbergfalk** [comment]
Thanks for the kind words @runemadsen! Glad the library has worked well for you :)

If I'm understanding your situation... were migrations once run without 30, and now that 30 exists in the lineup it is throwing the error? 

If that's the case, the error message could maybe be improved, like "found old migration not yet run" or "new migration out of order" or something like that. 

I'm not sure if it'd let you migrate down to 29 in this case either.

**Comment by runemadsen** [comment]
Yes, that's exactly what's happening. Perhaps a better error message could be helpful, since this happens quite often with multiple feature branches that introduce migrations. Thanks!
