### ISSUE TITLE
Please add support for node-mssql version 7.x

### ISSUE THREAD

**Issue by dreadwarrior** [rickbergfalk/postgrator#122]
Hi @rickbergfalk,

thank you for all your hard work and this very useful library.

Currently I'm trying to update a project to use mssql v7.1.1.
mssql v6.x has being marked as "legacy".

<img width="793" alt="mssql-nodejs" src="https://user-images.githubusercontent.com/277988/121646158-4d416000-ca95-11eb-84df-1b8f5a087b35.png">

While the tests running fine, the following error popped up during update:

> Package mssql version 7.x.x not tested
> Please raise issue to support mssql > 6.x.x

Can you add support for the new version please?

Thank you,

Tommy

**Comment by rickbergfalk** [comment]
Hi @dreadwarrior! Sorry for delay in getting to this. mssql 7 support is now available in postgrator 4.2.0

**Comment by dreadwarrior** [comment]
Thank you!
