### ISSUE TITLE
Support for socketPath option for mysql driver

### ISSUE THREAD

**Issue by terbooter** [rickbergfalk/postgrator#125]
mysql driver have `socketPath` [config option](https://www.npmjs.com/package/mysql#connection-options). 
It will be used if no `host` and `port` options
Implementation in driver [code](https://github.com/mysqljs/mysql/blob/master/lib/Connection.js#L74) 

This option very useful for Google Cloud environment. Here is [sample from gcloud doc how to use it](https://cloud.google.com/sql/docs/mysql/samples/cloud-sql-mysql-mysql-create-socket)

**Comment by rickbergfalk** [comment]
I'd be open to this,

I might end up enhancing the driver options so that the user of the library passes in a connection, which would remove the need for mapping all the common database configs and allow for a really flexible setup (see #90)

**Comment by rickbergfalk** [comment]
4.3 has the ability to pass an `execQuery` function, which allows you to connect your driver however you see fit. LMK if docs are confusing. There are some tests for reference.

This execQuery approach will be the only available option for v5.... leaves me with less to maintain and more flexibility for postgrator users.
