### ISSUE TITLE
Support *.cjs files in migration directory

### ISSUE THREAD

**Issue by perrin4869** [rickbergfalk/postgrator#136]
This would be useful in projects where `type` is set to `module`. The current workaround is to add a `package.json` with type `commonjs` instead...
It would be nice to also support `mjs` modules and `js` modules under `type: module` modules

**Comment by bajtos** [comment]
I ran into this issue too, when writing a JS migration file in a project with `"type": "module`.

While the solution proposed by @perrin4869 (support `.cjs` and `.mjs` extensions) is a good start, I feel it would be even better to implement first-class support for ESM modules.

**Comment by rickbergfalk** [comment]
I've been out of the loop on the nodejs migration to ESM. If I update postgrator to ES module natively, would it be able to use dynamic import for all files (.cjs, .mjs, and .js?)

**Comment by perrin4869** [comment]
I think it might be just a matter of using a dynamic import instead of a require, and that will work with node >= 12... But would need to try that first

**Comment by rickbergfalk** [comment]
I don't think I needed to convert to ESM to use `import()`, but I did. Not sure I entirely understand the edge cases of how old CJS plays with ESM and back, but I have confirmed that `.cjs` files are supported. 

Version 6 has been published to npm. There are no changes to the API other than ESM/cjs/mjs support.
