### ISSUE TITLE
Error when trying to get the current DB version

### ISSUE THREAD

**Issue by Kostanos** [rickbergfalk/postgrator#139]
When you run the migration for the first time, and trying to get the DB Version before run the migration, you will get error:

```
    const version = await postgrator.getDatabaseVersion();
    const maxVersionAvailable = await postgrator.getMaxVersion();
    console.log(`Migrate from ${version} to ${maxVersionAvailable}`);

    const appliedMigrations = await postgrator.migrate();
    console.log('Migrations finished', appliedMigrations);
```

```
Unexpected error:  relation "schemaversion" does not exist
```

It would be great if instead of raising error, the "version" constant just would be set to "0"

PS. As a workaround I'm using now:

```
    const version = await postgrator.getDatabaseVersion().catch(() => 0);
```

**Comment by bajtos** [comment]
Inside `postgrator.migrate()`, the first step is to create the `schemaversion` table:

https://github.com/rickbergfalk/postgrator/blob/e7d8bdd3c17cdec5fcb9fabd175065cfe7db4ce1/postgrator.js#L237

Only then we call `this.getDatabaseVersion()`:

https://github.com/rickbergfalk/postgrator/blob/e7d8bdd3c17cdec5fcb9fabd175065cfe7db4ce1/postgrator.js#L250

As a result, the error `relation "schemaversion" does not exist` is never encountered.

What options do we have to fix `postgrator.getDatabaseVersion()` to handle the missing `schemaversion` table?

1. We can update the documentation and tell users to call `postgrator.ensureTable()` before calling `postgrator.getDatabaseVersion()`. This feels rather cumbersome to me.

2. We can call `ensureTable()` as the first step of `getDatabaseVersion()`. Personally, I would find such behavior a bit surprising, as I don't expect getter functions to have side effects.

3. We can modify `ensureTable` to catch the "relation does not exist" error and return `0` instead. The tricky part is how to distinguish "relation does not exist" error from other kinds of errors. For example, when we cannot connect to the database, then we should re-throw the error. We may need to customize this error detection differently for each database server.

4. We can modify `ensureTable` to start with a query to check if the `schemaversion` table exists. Or perhaps modify the `Client.getDatabaseVersionSql()` to return a query that can handle the case where the table does not exist yet. IMO, this is the best option, as long as there is a way how to write such SQL query.

Thoughts?

**Comment by rickbergfalk** [comment]
Published a fix in 5.0.1. `getDatabaseVersion` will now return `undefined`.

**Comment by bajtos** [comment]
Thank you @rickbergfalk for the fixed version, it works well.

```js
  const dbVersion = (await postgrator.getDatabaseVersion()) ?? 0;
```

I noticed that TypeScript typings are not accurate now, I opened a pull request to fix them: https://github.com/rickbergfalk/postgrator/pull/142. 





> @bajtos I think a mix of 3 and 4 would be my opinion. I think we can check to see if schemaversion table exists, and if not return a `null` or `undefined` to represent that there is no table so there's no version to report. Technically if someone wanted to they could have a migration 0.
> 
> All other errors could be thrown as they are today. Does this seem like a reasonable solution?

Yes :+1:

On the second thought, I am not sure if it's a good idea to return `undefined`.

The current implementation is returning `0` when the `schemaversion` table is empty.

So now we have the following possible results:
- `undefined` when the table does not exist yet
- `0` when the table exists but is empty
- `number` when some migration have been already applied

IMO, since we were already returning `0` when no migrations have been applied yet, I think it's ok to return `0` when the `schemaversion` table was not created yet.

Thoughts?

**Comment by rickbergfalk** [comment]
@bajtos good catch! 0 would be more convenient since it is already returned.

**Comment by rickbergfalk** [comment]
Might be unnecessary, but since a version was published with the solution being `undefined`, I'm going to consider this a breaking change and publish as a new major just to be safe.

**Comment by bajtos** [comment]
> @bajtos good catch! 0 would be more convenient since it is already returned.

Yes, 0 is easier to use. Now I can simplify my code snippet from https://github.com/rickbergfalk/postgrator/issues/139#issuecomment-1047630285 as follows:


```ts
const dbVersion = await postgrator.getDatabaseVersion();
```


> Might be unnecessary, but since a version was published with the solution being `undefined`, I'm going to consider this a breaking change and publish as a new major just to be safe.

👍🏻 

Thank you @rickbergfalk for addressing my comments, I appreciate the time and effort you are putting into maintaining this project ❤️
