### ISSUE TITLE
Postgres items such as CREATE INDEX CONCURRENTLY do not work

### ISSUE THREAD

**Issue by nick-gray** [rickbergfalk/postgrator#16]
Some items cant be run in transactions or be multi line commands such as 
CREATE INDEX CONCURRENTLY

http://www.postgresql.org/docs/9.5/static/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY

Regular index builds permit other regular index builds on the same table to occur in parallel, but only one concurrent index build can occur on a table at a time. In both cases, no other types of schema modification on the table are allowed meanwhile. Another difference is that a regular CREATE INDEX command can be performed within a transaction block, but CREATE INDEX CONCURRENTLY cannot.

Would be good if this was able to support this without creating one file for each index. Any other suggestions?

**Comment by rickbergfalk** [comment]
I'm not too familiar with postgres in this area yet. Are there any keywords that can be used to separate the commands out? SQL Server for example has a GO keyword that separates commands that can't be run in a single implicit transaction...

If there isn't a keyword/terminator that works like that for Postgres, what if we had some sort of keyword/symbol that was used to split postgrator migration files up and run individually behind the scenes? It could even be embedded in a SQL comment to get out of the way and keep sql files sql. 

```sql
CREATE INDEX CONCURRENTLY IX_1 ...

-- NEW_POSTGRATOR_BATCH       (or whatever terminology would be correct here)

CREATE INDEX CONCURRENTLY IX_2 ...
```

Let me know what you find out or what your thoughts are on a solution :)

**Comment by nick-gray** [comment]
Yeah this sounds good, we could just have some flag at the top of the file to treat it like psql default execution (ie each line just run as a separate transaction).

**Comment by rickbergfalk** [comment]
I'm still thinking about this 😂 

My initial thought about allowing the separator could be really inconvenient from a migration standpoint. If 2 `CREATE INDEX CONCURRENTLY` statements are in 1 migration file, and the 2nd fails, someone would be left with a partially implemented migration. 

So then I thought... someone could counter this problem with `CREATE INDEX CONCURRENTLY IF NOT EXISTS` to skip on a second migration run, except if there's a failure during concurrent index creation, the index can be "created" but left in a bad "invalid" state. (not sure if postgres would recreate in that scenario or not)

This could be countered with dropping indexes if they exist, and then recreating them. But in the failure case above the first index created successfully would be dropped unnecessarily, and recreated. This could get expensive to run, take a long time, and also leave the database without an index for a while.

So now I'm leaning towards maybe having a postgres-specific utility function that ensure's postgres indexes exist, creates them concurrently, and then once all that is done, marking the migration as implemented...

**Comment by rickbergfalk** [comment]
This is an old issue, but decided to not mess with this at all. I've not used postgrator for quite some time, but I'm also hesitant to break migration scripts up to make them compatible. For example, postgrator supported splitting on the `GO` keyword for MS SQL Server, which essentially created different transactions, but ultimately this was somewhat dangerous because it allowed partial migrations to be applied.

Not really sure how to handle this using postgrators approach to be honest - If anyone is looking for this functionality I'd suggest looking at a more postgres-specific migration tool.
