### ISSUE TITLE
Support sqlite migrations with semicolon

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/postgrator#166]
Certain sqlite migrations containing a semicolon don't work, such as triggers. [See this discussion](https://github.com/rickbergfalk/postgrator/pull/150/files#r1731924949) for context.

**Comment by zmeyc** [comment]
https://github.com/rickbergfalk/postgrator/pull/167
@rickbergfalk @mcollina Please review

**Comment by zmeyc** [comment]
It appears Mocha 10 dropped Node 12 support: https://github.com/mochajs/mocha/releases/tag/v10.0.0
But .circleci/config.yml is still using `circleci/node:12.22` image.

**Comment by rickbergfalk** [comment]
@zmeyc published 7.3.0 to npm. Thanks for taking this on!
