### ISSUE TITLE
Update glob

### ISSUE THREAD

**Issue by bbrk24** [rickbergfalk/postgrator#169]
When installing postgrator 7.3 in a new project, I noticed these warnings:

```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

inflight is a dependency of glob, so both of these would be resolved by updating to a newer version of glob.

**Comment by rickbergfalk** [comment]
glob is updated in 8.0.0. No postgrator API changes... Newer glob doesn't support older nodes, hence the major rev bump.

**Comment by bbrk24** [comment]
Thanks for getting to this so quickly!
