### ISSUE TITLE
Not seeing MD5 get added to schemaversion table

### ISSUE THREAD

**Issue by hlfshell** [rickbergfalk/postgrator#17]
Running on windows w/ mysql, I'm seeing md5 get calculated on the reported migrations on the .migrate() callback, but I'm not seeing it placed in the database table.

Am I incorrect in assuming that the md5 should be store here to confirm matching of SQL files?

**Comment by rickbergfalk** [comment]
Hi @hlfshell - You are correct in assuming that the md5 is used to verify matching SQL files. It has only been implemented for postgres so far. I don't believe there was any particular reasoning for this at the time.

Commit for reference: https://github.com/rickbergfalk/postgrator/pull/2/commits/2009afa8beb436da9cbb9fd3c7889ed31c35d40d

**Comment by rickbergfalk** [comment]
I know this is *really* delayed, but... this is now implemented for mysql and sql server as of v3 🐢
