### ISSUE TITLE
Postgrator assumes that all the files in the script folder are migrations...

### ISSUE THREAD

**Issue by lonewarrior556** [rickbergfalk/postgrator#28]
Does this always HAVE to be the case?  Assume I have  a "create-db.sql" in there,.. 

it shouln't be labeled 000.create-db.sql if its not part of the migration,..

but, since its in there, this line
https://github.com/rickbergfalk/postgrator/blob/7b3ef69304443c1d41012bffb769c1c7fbe47424/postgrator.js#L148

will return  `max` as `NaN` when calling getVersions() 

if a NaN filter could be added to the line then it would remove the NaN entries and provide the latest correctly labeled migration script as max.

`Math.max.apply(null, migrations.map(function (migration) { return migration.version }).filter(function(version){ return !isNaN(version) }) )`

Can this be added?

**Comment by rickbergfalk** [comment]
Definitely - I'm onboard with that change. The filter could also be done in the getMigrations() function too. 

Want to send in a PR? Otherwise I can take care of it sometime tonight or later this week.

**Comment by lonewarrior556** [comment]
Pr created https://github.com/rickbergfalk/postgrator/pull/32
Thanks!

**Comment by rickbergfalk** [comment]
#32 merged. Thanks again!
