### ISSUE TITLE
Possibility to install chosen DB engines

### ISSUE THREAD

**Issue by Kostanos** [rickbergfalk/postgrator#29]
Currently this module installs mssql, mysql and pg.

In 99% of use cases, I use only one of those DB at a time. Would be great to have possibility to install postgrator without any DB engine and after add one or multiples that are required.

**Comment by rickbergfalk** [comment]
I'd be open to this change I think. The downside to this approach though would be having to handle major version changes for a given driver, but I suppose that forces some upkeep and maintenance for this module.

**Comment by Kostanos** [comment]
as all requires of pg/mysql/mssql are optional in the code, I think the better approach is to just remove them from package.json. And add in readme that the necessary engine should be installed apart as dependency.

I saw the similar approach on another DB related tool (don't remember which one)

**Comment by rickbergfalk** [comment]
Merged. Thanks again @Kostanos!
