### ISSUE TITLE
Can we expose getMigrations()?

### ISSUE THREAD

**Issue by lonewarrior556** [rickbergfalk/postgrator#34]
https://github.com/rickbergfalk/postgrator/blob/5608ab730c125cfa9759322f9a455990355e4eab/postgrator.js#L45

The comment says it's `Internal function
  Reads the migration directory for all the migration files.
  It is SYNC out of laziness and simplicity` and isn't exported, however it would be very useful to have for ie, checking if the requested migration is a valid migration before attempting.

Is there a reason it should only be internal?

**Comment by lonewarrior556** [comment]
Alternatively, We can add 

`versions.all = migrations` to getVersions()

 https://github.com/rickbergfalk/postgrator/blob/5608ab730c125cfa9759322f9a455990355e4eab/postgrator.js#L145-L160

**Comment by rickbergfalk** [comment]
I think initial reasoning was to limit the interface that needs to be maintained for version maintenance. Once its exposed, its now part of the API that needs to be considered for breaking changes.

I'm open to it being exported.

**Comment by lonewarrior556** [comment]
That makes sense,  the alternative solutions seems easier and better: 
since getVersions() is already exposed, and it makes sense for it to also return all available migrations along with max and current. 

https://github.com/rickbergfalk/postgrator/pull/36

**Comment by rickbergfalk** [comment]
merged

**Comment by rickbergfalk** [comment]
@lonewarrior556 check out the API changes in v3. I didn't plan on redoing it all but I was slightly horrified when I tried to make sense of all my old callback code :)

I embraced exposing more utility methods, and I'm open to adding more as long as they make sense and are tested :)
