### ISSUE TITLE
Thank you Rick!

### ISSUE THREAD

**Issue by marcuspoehls** [rickbergfalk/postgrator#57]
Hi Rick,

thank you so much for this project!
I needed to import a `.sql` file into MSSQL and failed with all other approaches. Finally found Postgrator and it works like a charm.

Easy to set up, easy to use. Great that is uses Promises out of the box so I can keep the async/await style in my app. Really awesome!

Thank you Rick! :heart:

**Comment by rickbergfalk** [comment]
You're welcome @marcuspoehls! And thanks for the kind message! Glad you are finding the project useful :)
