### ISSUE TITLE
Script never ends on error during migration.

### ISSUE THREAD

**Issue by Kostanos** [rickbergfalk/postgrator#58]
I have a simple migration script:

```
const Postgrator = require('postgrator');

const postgrator = new Postgrator({
  migrationDirectory: __dirname + '/migrations',
  schemaTable: 'postgrator',
  driver: 'pg',
  host: process.env.PGHOST,
  port: process.env.PGPORT || 5432,
  database: process.env.PGDATABASE,
  username: process.env.PGUSER,
  password: process.env.PGPASSWORD,
});

postgrator.migrate()
.then(migrations => {
  console.log('Migrations finished', migrations);
})
.catch(err => {
  console.error('DB Migration error', err);
});
```

The problem is that running:

```
node migration.js
```
will never ends if there is any error on any of the migration step.
If there is no errors, everything works great.

**Comment by rickbergfalk** [comment]
Thanks for reporting this - I suspect the database connections aren't being closed on error. Will have to look into that... For time being if this is a standalone script, a workaround could be to call process.exit(1).
