### ISSUE TITLE
Postgrator fails when database has  already schemaversion table with different schema, mssql

### ISSUE THREAD

**Issue by swamy526** [rickbergfalk/postgrator#60]
For example, if I have a table called meta.SchemaVersion in database. Now I executed postgrator , it throwing error like 
Error: Cannot find the object "schemaversion" because it does not exist or you do not have permissions.

So fix this issue, it is better to include `dbo.` before the schemaTable property value of DEFAULT_CONFIG. Something like

```
const DEFAULT_CONFIG = {
  schemaTable: 'dbo.schemaversion',
  validateChecksums: true
}

instead of 

const DEFAULT_CONFIG = {
  schemaTable: 'schemaversion',
  validateChecksums: true
}

```
in case of mssql server.

**Comment by rickbergfalk** [comment]
Hi @swamy526 

I believe SQL Server will use the default schema of the user used to connect to the database. The postgres implementation is allowed to set a schemaTable as 'schemaname.tablename' and have it be respected. The same approach could be added for the SQL Server implementation, which would allow setting which schemaTable you'd like to use specifically
