### ISSUE TITLE
Support for DATABASE_URL environment variable

### ISSUE THREAD

**Issue by raine** [rickbergfalk/postgrator#62]
I'm evaluating different tools for running migrations and noticed there's no way to configure postgrator with a single environment variable that contains the database URL. Using a variable like this to configure a db client is quite common these days. Even `psql` supports it.

**Comment by rickbergfalk** [comment]
Hi @raine - postgrator is something you'd need to reference inside your application or script. If you'd like you can reference the environment variable in your application or script, parse it if necessary, then pass it to postgrator
