### ISSUE TITLE
Support mssql version 5

### ISSUE THREAD

**Issue by jon-shipley** [rickbergfalk/postgrator#84]
Many thanks for your work on this package.

Now that `mssql` version 5 is out please would you consider adding official support for it?
https://github.com/tediousjs/node-mssql/releases

At the moment I get a warning message

```
Package mssql version 5.x.x not tested
Please raise issue to support mssql > 4.x.x
```

**Comment by rickbergfalk** [comment]
Thanks @jon-shipley! 

Support for mssql 5 has been added to postgrator 3.10 now available on npm.
