### ISSUE TITLE
Usage with existing database

### ISSUE THREAD

**Issue by tahmidsadik** [rickbergfalk/postgrator#88]
Hi @rickbergfalk, great work with `postgrator`.
I am trying to integrate `postgrator` to an existing application but not quite sure about how to integrate it with an existing database. 
One way to solve this is by using a `baseline` version of the existing database from which to start versioning. Is this feature supported in `postgrator`? Or are there other better ways to handle this use case?

**Comment by dkline** [comment]
Using a baseline script or scripts works for sure. Though, you'd have to be a little careful not to run the database create script on an existing production system.

Another option if you are always going to be starting from an existing database/backup is to have the first script be the first postgrator-managed change.

**Comment by theashguy** [comment]
I've recently done this with a large MySQL database that had no migrations (T_T).

Pattern (for MySQL) is:

1. Dump your db schema (not data) to an SQL file.
2. Remove all lines that start with "DROP TABLE IF EXISTS" to prevent the dumped SQL from dropping all of your current data tables.
3. Find & Replace all "CREATE TABLE" to "CREATE TABLE IF NOT EXISTS" allowing the migration to run over your current schema without freaking out that the tables are already there, and therefore set up the migration schema.
4. Use this content as your up migration.
5. Get all table names (find and copy "CREATE TABLE" lines and then clear them up).
6. Set this to your down migration, if it works then good! But in all liklihood, you have some gnarly foreign key issues.
7. To get around foreign key issues set the first line of your down migration to be  `SET FOREIGN_KEY_CHECKS = 0;` and the last line to be `SET FOREIGN_KEY_CHECKS = 1;` which will disable foreign key checks while the tables are being dropped. 
8. Profit.

Similar patterns will exist for the other supported db types. Go out and find em!
