### ISSUE TITLE
Support for node-mssql version 6.0.0

### ISSUE THREAD

**Issue by sealmes** [rickbergfalk/postgrator#92]
Version 6.0.0 is out for the node-mssql library. This includes a bump of two major versions for the Tedious library. 

Our unit tests (which run postgrator migrations) all pass with node-mssql 6.0.0, but we get a message:

> Package mssql version 6.x.x not tested
> Please raise issue to support mssql > 5.x.x

This is me raising an issue to support mssql :) :)

**Comment by rickbergfalk** [comment]
Thanks for raising the issue :)

Warning should be gone in 3.11 now available on npm
