### ISSUE TITLE
has an issue with non default schema for mssql

### ISSUE THREAD

**Issue by mkhatuntcov-korewireless** [rickbergfalk/postgrator#94]
Posgrator `3.10.1` is not supporting non default schema for mssql. 

There is an option:
https://github.com/rickbergfalk/postgrator/pull/93

@rickbergfalk Could you please take a look?

**Comment by rickbergfalk** [comment]
Thanks again @mkhatuntcov-korewireless - your fix has been published to npm available in version 3.11

**Comment by mkhatuntcov-korewireless** [comment]
No worries. Thank you for supporting postgrator for us!
