### ISSUE TITLE
Using upper case characters in schemaTable with postgresql lead to an error

### ISSUE THREAD

**Issue by Waelmio** [rickbergfalk/postgrator#98]
Hello !

As the title said, using upper case characters in schemaTable with postgresql lead to an error.
It should be because of these lines in ```lib/PostgresClient.js```:
```
if (schema[1]) {
      tableName = schema[1]
      schemaSql = `AND table_schema = '${schema[0]}'`
    } else if (config.currentSchema) {
      schemaSql = `AND table_schema = '${config.currentSchema}'`
    }

    return `
      SELECT column_name
      FROM INFORMATION_SCHEMA.COLUMNS 
      WHERE table_name = '${tableName}'
      ${tableCatalogSql}
      ${schemaSql};
    `
```
Quotes around a parameter make the search case-sensitive (https://dev.to/lefebvre/dont-get-bit-by-postgresql-case-sensitivity--457i) but tables are created in full lower case.
So the query return there is no table and the app try to recreate one... Which is already here.

**Comment by rickbergfalk** [comment]
Postgres schema table is now case sensitive as of v5, which is now available on npm
